services:
  - type: web
    name: youtube-summarizer-backend
    env: python
    plan: free
    buildCommand: cd backend && chmod +x build.sh && ./build.sh
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: YOUTUBE_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false 